apiVersion: batch/v1
kind: Job
metadata:
  name: mithril-bootstrap-job
  namespace: testnet
  labels:
    app: mithril-bootstrap
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: mithril-bootstrap
    spec:
      restartPolicy: Never
      volumes:
        - name: cardano-preprod-db-mithril-pvc
          persistentVolumeClaim:
            claimName: cardano-preprod-db-mithril-pvc
        - name: mithril-keys
          configMap:
            name: mithril-verification-keys
      containers:
        - name: mithril-bootstrap
          image: ghcr.io/input-output-hk/mithril-client:main-e6135c6
          env:
            - name: AGGREGATOR_ENDPOINT
              value: https://aggregator.release-preprod.api.mithril.network/aggregator
            - name: GENESIS_VERIFICATION_KEY
              valueFrom:
                configMapKeyRef:
                  name: mithril-verification-keys
                  key: genesis.vkey
            - name: ancillary-verification-key
              valueFrom:
                configMapKeyRef:
                  name: mithril-verification-keys
                  key: ancillary.vkey
          args:
            - cardano-db
            - download
            - latest
            - --download-dir
            - /db
            - --include-ancillary
          volumeMounts:
            - name: cardano-preprod-db-mithril-pvc
              mountPath: /db
            - name: mithril-keys
              mountPath: /keys
