apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cardano-preprod-db-mithril-pvc
  namespace: testnet
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cardano-db-sc
  resources:
    requests:
      storage: 25Gi
  selector:
    matchLabels:
      app: cardano-preprod-node
      cardano-preprod-node-type: mithril-bootstrap
  volumeName: cardano-preprod-db-mithril-pv
