apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cardano-preprod-statefulset
  labels:
    app: cardano-preprod-node
  namespace: testnet
spec:
  serviceName: cardano-preprod
  replicas: 1
  selector:
    matchLabels:
      app: cardano-preprod-node
  template:
    metadata:
      labels:
        app: cardano-preprod-node
    spec:
      volumes:
        - name: cardano-preprod-config-pvc
          persistentVolumeClaim:
            claimName: cardano-preprod-config-pvc
        - name: cardano-preprod-db-pvc
          persistentVolumeClaim:
            claimName: cardano-preprod-db-pvc
      containers:
        - name: cardano-preprod-node
          image: ghcr.io/intersectmbo/cardano-node:10.3.1
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: cardano-preprod-config-pvc
              mountPath: /data
            - name: cardano-preprod-db-pvc
              mountPath: /db
          args:
            - run
            - --topology
            - /data/topology.json
            - --socket-path
            - /data/node.socket
            - --database-path
            - /db
            - --config
            - /data/config.json
  volumeClaimTemplates:
    - metadata:
        name: cardano-preprod-config-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: cardano-config-sc
        resources:
          requests:
            storage: 25Gi
    - metadata:
        name: cardano-preprod-db-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: cardano-db-sc
        resources:
          requests:
            storage: 25Gi