apiVersion: v1
kind: Service
metadata:
  name: {{ include "cardano.fullname" . }}-headless
  namespace: {{ .Release.Namespace | quote }}
  labels: 
    {{- include "cardano.labels" . | nindent 4 }}
  annotations:
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: tcp-node
      port: {{ .Values.service.port }}
      targetPort: node
  selector:
    {{- include "cardano.selectorLabels" . | nindent 4 }}
