{{- if .Values.vault.csi.enabled }}
{{- $fullName := include "cardano.fullname" . }}
{{- $spcHot := printf "%s-spc-%s" $fullName "hot" }}
{{- $spcCold := printf "%s-spc-%s" $fullName "cold" }}

---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $spcHot }}
spec:
  provider: azure
  parameters:
    keyvaultName: {{ .Values.vault.csi.hotVaultName }}
    usePodIdentity: "false"
    useVMManagedIdentity: "true"         
    userAssignedIdentityID: {{ .Values.vault.csi.userAssignedIdentityID | default "" }}
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: kesSkey
          objectType: secret
          objectVersion: ""
        - |
          objectName: vrfSkey
          objectType: secret
          objectVersion: ""
        - |
          objectName: nodeCert
          objectType: secret
          objectVersion: ""
    tenantId: {{ .Values.vault.csi.tenantId }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $spcCold }}
spec:
  provider: azure
  parameters:
    keyvaultName: {{ .Values.vault.csi.coldVaultName }}
    usePodIdentity: "false"
    useVMManagedIdentity: "true"         
    userAssignedIdentityID: {{ .Values.vault.csi.userAssignedIdentityID | default "" }}
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: coldVkey
          objectType: secret
          objectVersion: ""
        - |
          objectName: coldSkey
          objectType: secret
          objectVersion: ""
        - |
          objectName: coldCounter
          objectType: secret
          objectVersion: ""
    tenantId: {{ .Values.vault.csi.tenantId }}
{{- end }}
