apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cardano-preprod-deployment
  labels:
    app: cardano-preprod-deployment
  namespace: cardano
spec:
  serviceName: cardano-preprod
  # Control the number of relays here (you'll need enough volumes to cover them!)
  replicas: 1
  selector:
    matchLabels:
      app: cardano-preprod-node
      cardano-preprod-node-type: relay
  template:
    metadata:
      labels:
        # I added two labels to make it easy to select either "all nodes" or
        # "just relays" or just producer node"
        app: cardano-preprod-node
        cardano-preprod-node-type: relay
    spec:
      containers:
        - name: cardano-preprod-relay
          image: ghcr.io/intersectmbo/cardano-node:10.3.1
          # Expose both the cardano-node port and the /metrics endpoint port.
          ports:
            - containerPort: 12798
            - containerPort: 4000
          # Mount the data volume at /data (see the Volume Claim below)
          volumeMounts:
            - name: cardano-pvc
              mountPath: /data
          # My configuration lives inside the mounted /data folder, and that's also where
          # the db data should be written
          args: ["run", "--config", "/data/cardano/preprod/config.json",
           "--topology", "/data/cardano/preprod/topology.json",
           "--database-path", "/data/db",
           "--socket-path", "/data/node.socket",
           "--port", "4000"]
  volumeClaimTemplates:
    - metadata:
        name: cardano-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        # This storageClassName is used on the previously defined volume that
        # provides storage on the host machine
        storageClassName: cardano-sc
        resources:
          requests:
            storage: 20Gi