apiVersion: v1
kind: Service
metadata:
  name: cardano-preprod-relay-service
spec:
  type: NodePort
  selector:
    app: cardano-preprod-node
    cardano-node-type: relay
  ports:
    - port: 30801
      nodePort: 30801
      targetPort: 4000