apiVersion: v1
kind: Service
metadata:
  name: cardano-mainnet-relay-service
spec:
  type: NodePort
  selector:
    app: cardano-mainnet-node
    cardano-mainnet-node-type: relay
  ports:
    # Export port 30801 pointing at port 4000 on the pod(s)
    - port: 30801
      nodePort: 30801
      targetPort: 4000