apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-sync-data-pvc
  namespace: testnet
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  storageClassName: cardano-sc

---

apiVersion: v1
kind: PersistentVolume
metadata:
  # To provide volumes for multiple nodes, this section is
  name: cardano-pv
  namespace: testnet
  labels:
    app: cardano-preprod-node
    cardano-preprod-node-type: relay
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce # Only allow one container to use this volume
  persistentVolumeReclaimPolicy: Delete
  storageClassName: cardano-sc
  local:
    path: /data/cardano/preprod
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          # Restrict this volume to a specific Kubernetes node by hostname
          - key: kubernetes.io/hostname
            operator: In
            values:
              - 133-worker-01

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cardano-sc
spec: {}
  provisioner: kubernetes.io/no-provisioner
  reclaimPolicy: Retain
  volumeBindingMode: WaitForFirstConsumer