apiVersion: apps/v1
kind: Deployment
metadata:
  name: cardano-node-db-sync
  namespace: testnet
  labels:
    app: cardano-node-db-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cardano-node-db-sync
  template:
    metadata:
      labels:
        app: cardano-node-db-sync
    spec:
      nodeSelector:
        kubernetes.io/hostname: 133-worker-01
      volumes:
        - name: db-sync-storage
          persistentVolumeClaim:
            claimName: cardano-node-db-sync-pvc
        - name: node-ipc-socket
          emptyDir: {} # Shared IPC socket volume for cardano-db-sync and cardano-node
      containers:
        - name: cardano-db-sync
          image: ghcr.io/intersectmbo/cardano-db-sync:13.6.0.5
          envFrom:
            - configMapRef:
                name: cardano-db-sync-config
            - secretRef:
                name: cardano-db-sync-secret
          env:
            - name: CARDANO_NODE_SOCKET_PATH
              value: "/node-ipc/node.socket" # Important: Must match the node container's socket path
          volumeMounts:
            - name: db-sync-storage
              mountPath: /var/lib/cexplorer
            - name: node-ipc-socket
              mountPath: /node-ipc
