apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cardano-node-db-sync-pvc
  namespace: testnet
spec:
  storageClassName: cardano-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  # To provide volumes for multiple nodes, this section is
  name: cardano-node-db-sync-pv
  namespace: testnet
  labels:
    app: cardano-preprod-node
    cardano-node-type: relay
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cardano-sc
  local:
    path: /data/postgres/
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          # Restrict this volume to a specific Kubernetes node by hostname
          - key: kubernetes.io/hostname
            operator: In
            values:
              - 133-worker-01
